### ISSUE TITLE
I bought this book and threw my money in the trash

### ISSUE THREAD

**Issue by EdnaldoNeimeg** [Swiftam/book-node-mongodb-backbone#46]
The author did not fix the versions of dependencies and nothing works (2015).
The texts are poorly explained and the author never says where to store the files.

**Comment by Swiftam** [comment]
Thanks for your comments

The lib versions are listed in the book and on Github. A lot has changed in the Node.js world in the 3 years since the book was developed&released.

on p.8 it mentions that Node.js was at v 0.8.12, cutting edge stuff at the time but backwards-compatibility has not been on the minds of developers since that time. Hopefully things will get better after the 1.0 release.

In fact dependency versions are listed right in the packages file in the repo. If you specify these versions rather than grabbing the latest from npm (e.g. drop packages.json in the directory and run 'npm install' rather than installing each package by hand) , the code samples will run a lot better.

{
    "name": "my-social-network",
    "version": "0.0.1",
    "private": true,
    "dependencies": {
      "express": "~3.0.0",
      "jade": ">= 0.0.1",
      "mongoose": ">= 2.6.5",
      "nodemailer": "0.3.20",
      "connect": ">= 1.9.1",
      "socket.io": "~0.9",
      "cookie": "0.0.4"
  }
}

**Comment by EdnaldoNeimeg** [comment]
Thanks, i'll try run it again with these suggestions.
